trigger:
 branches:
  include:
    - main
    - dev

variables:
  - name: linuxImageName 
    value: 'ubuntu-latest'
  - name: widowImageName
    value: 'windows-latest'
  - name: dockerfilePath
    value: 'src/Restaurent.WebAPI/Dockerfile'
  - name: tag
    value: $(Build.BuildId)

stages:
 - stage: Build
   displayName: Build and push stage
   jobs:
    - job: Build
      displayName: Docker Build
      pool:
       vmImage: $(linuxImageName)
      steps:
      - task: Docker@2
        inputs:
          containerRegistry: 'dockerhub-service-connection'
          repository: 'adityadocker02/restaurantapi'
          command: 'buildAndPush'
          Dockerfile: $(dockerfilePath)
          tags: |
            $(tag)
           buildContext: '.'
