trigger:
 branches:
  include:
    - main
    - dev

variables:
  - name: linuxImageName 
    value: 'ubuntu-latest'
  - name: widowImageName
    value: 'windows-latest'
  - name: dockerfilePath
    value: 'src/Restaurent.WebAPI/Dockerfile'
  - name: tag
    value: $(Build.BuildId)

stages:
 - stage: Build
   displayName: Build and push stage
   jobs:
    - job: Build
      displayName: Docker Build
      pool:
       vmImage: $(linuxImageName)
      steps:
      - task: Docker@2
        inputs:
          containerRegistry: 'dockerhub-service-connection'
          repository: 'adityadocker02/restaurantapi'
          command: 'buildAndPush'
          Dockerfile: $(dockerfilePath)
          tags: |
            $(tag)
            latest
          buildContext: '.'

 - stage: Test
   displayName: Test and publish result stage
   jobs:
   - job: RunTest
     displayName: Run Tests
     pool:
      vmImage: $(widowImageName)
     steps:
       - checkout: self
         displayName: Checkout source code
      
       - task: NuGetToolInstaller@1
         displayName: Install NugetTool

       - task: NuGetCommand@2
         displayName: Restore Nuget Packages
         inputs:
           command: 'restore'
           restoreSolution: '**/*.sln'

       - task: MSBuild@1
         displayName: Build solution
         inputs:
           solution: '**/*.sln'
           msbuildArchitecture: 'x64'
           platform: 'Any CPU'
           configuration: 'Debug'

       - task: VSTest@3
         displayName: Test solution
         inputs:
           testSelector: 'testAssemblies'
           testAssemblyVer2: |
             **\bin\**\*Tests.dll
             !**\*TestAdapter.dll
             !**\obj\**
           searchFolder: '$(System.DefaultWorkingDirectory)'
           runTestsInIsolation: true
           codeCoverageEnabled: true
